/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/modal/BaseModal.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    DefaultModal: typeof import('./src/components/modal/DefaultModal.vue')['default']
    DialogHost: typeof import('./src/components/modal/DialogHost.vue')['default']
    Img: typeof import('./src/components/media/Img.vue')['default']
    Input: typeof import('./src/components/form/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./src/components/media/Svg.vue')['default']
    TextArea: typeof import('./src/components/form/TextArea.vue')['default']
    TextField: typeof import('./src/components/form/TextField.vue')['default']
  }
}
