import { readFileSync } from 'node:fs'
import js from '@eslint/js'
import globals from 'globals'
import pluginVue from 'eslint-plugin-vue'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import skipFormatting from '@vue/eslint-config-prettier/skip-formatting'

// unplugin-auto-import writes an eslintrc-shaped file on every dev/build.
// Flat config wants { name: 'readonly' }, so map the keys across.
const autoImportGlobals = Object.fromEntries(
  Object.keys(JSON.parse(readFileSync('./.eslintrc-auto-import.json', 'utf8')).globals).map(
    name => [name, 'readonly']
  )
)

const isProduction = process.env.NODE_ENV === 'production'

export default defineConfigWithVueTs(
  {
    ignores: [
      'dist/**',
      'dist-ssr/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      '.output/**',
      '**/*.tsbuildinfo',
      // generated by unplugin-* on every dev/build
      'auto-imports.d.ts',
      'components.d.ts',
      '.eslintrc-auto-import.json',
    ],
  },

  js.configs.recommended,
  pluginVue.configs['flat/strongly-recommended'],
  vueTsConfigs.recommended,

  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...autoImportGlobals,
      },
    },

    rules: {
      // Vue
      'vue/multi-word-component-names': 'off',
      'vue/no-unused-vars': 'error',
      'vue/component-definition-name-casing': ['error', 'PascalCase'],
      'vue/component-name-in-template-casing': ['error', 'PascalCase'],
      'vue/prop-name-casing': ['error', 'camelCase'],
      'vue/attribute-hyphenation': ['error', 'always'],
      'vue/v-on-event-hyphenation': ['error', 'always'],
      'vue/require-default-prop': 'error',
      'vue/require-prop-types': 'error',
      'vue/order-in-components': 'error',
      'vue/this-in-template': 'error',
      'vue/block-tag-newline': 'error',
      // renamed from vue/component-tags-order (deprecated in eslint-plugin-vue 9.16)
      'vue/block-order': ['error', { order: ['script', 'template', 'style'] }],
      'vue/define-macros-order': [
        'error',
        { order: ['defineOptions', 'defineProps', 'defineEmits', 'defineSlots'] },
      ],

      // TypeScript
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-inferrable-types': 'error',

      // General
      'no-console': isProduction ? 'warn' : 'off',
      'no-debugger': isProduction ? 'warn' : 'off',
      'prefer-const': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-template': 'error',
      'prefer-arrow-callback': 'error',
    },
  },

  {
    files: ['**/*.vue'],
    rules: {
      // the Vue compiler resolves these; auto-imports make them invisible to ESLint
      'no-undef': 'off',
    },
  },

  {
    files: ['**/*.spec.{js,ts,jsx,tsx}', '**/*.test.{js,ts,jsx,tsx}'],
    rules: {
      'no-console': 'off',
    },
  },

  // must stay last: turns off everything Prettier owns
  skipFormatting
)
